# QuickShop Reremake FindItem AddOn

# Requires finditem.use permission node
# Color codes are supported
# If you want to keep a field empty, make it as ""
# NEVER leave it empty without quotes, or bad things will happen!
# Do /finditem reload to reload this config (Requires finditem.reload permission node)

# Prefix that will be shown in chat for any message from this plugin
PluginPrefix: "&a&l[Shop Search] &r"

# Below messages will be prefixed with the above specified prefix
FindItemCommand:
  IncorrectUsageMessage: "&cIncorrect usage! Try &e/finditem &a{TO-BUY | TO-SELL} &6{item type | item name}"
  InvalidMaterialMessage: "&cEither no shops were found or you provided an invalid item! &fTry selecting from autofill."
  UnsafeShopAreaMessage: "&cThe area around the shop is unsafe!"

# Set it to true to allow players to teleport to the shop directly
# when they click on the shop result in GUI
allow-direct-shop-tp: true

# Enabling this will spam your console with logs from the plugin
# Set this to true only for debugging purposes
# If set to false, some error messages can still get through if they require immediate attention
debug-mode: false