# QuickShop Reremake Shop Search AddOn

# Requires finditem.use permission node for players
# Requires finditem.admin permission node for admin commands (/finditem reload | /finditem restart)
# Do '/finditem reload' to reload this config and update your changes
# Do '/finditem restart' to restart the plugin (NOT RECOMMENDED IN MOST CASES)
# Color codes are supported below
# If you want to keep a field empty, make it as ""
# DON'T leave it empty without quotes, or bad things might happen!

# PS: If you do '/qs reload' this addon will stop working as QuickShop API
# doesn't work after the plugin reload command is run
# In such case, please restart your server.


# Prefix that will be shown in chat for any message from this plugin
plugin-prefix: "&a&l[Shop Search] &r"


# Below messages will be prefixed with the above specified prefix
find-item-command:
  incorrect-usage-message: "&cIncorrect usage! Try &e/finditem &a{TO-BUY | TO-SELL} &6{item type | item name}"
  invalid-material-message: "&cEither no shops were found or you provided an invalid item! &fTry selecting from autofill."
  shop-search-loading-message: "&7Searching..."
  no-shop-found-message: "&7No shops found!"
  find-item-command-no-permission-message: "&cNo permission!"
  # Below are tab-autocompletes for categorizing between buying/selling shops
  # There cannot be spaces in between
  # NEEDS A SERVER RESTART IF CHANGED
  to-buy-autocomplete: "TO-BUY"
  to-sell-autocomplete: "TO-SELL"


# Shop sorting methods:
# 1 - Random
# 2 - Based on prices (lower to higher)
# 3 - Based on stocks (higher to lower)
# Enter your choice of method below
shop-sorting-method: 2

# Set it to true to search shops on loaded chunks only.
# When set to false, it searches through all shops regardless
# of them being on loaded chunks or not.
# If a shop is present in chunk which is currently unloaded,
# it loads the chunk to search for items in containers.
search-loaded-shops-only: false

shop-search-gui-title: "&l» &rShops"

# Shop Search GUI Item Lore
# Placeholders for shop-item-lore:
# {ITEM_PRICE}          -> Item price in shop
# {SHOP_STOCK}          -> Remaining stock in shop
# {SHOP_OWNER}          -> Owner of shop
# {SHOP_LOC}            -> Shop coordinates
# {SHOP_WORLD}          -> Name of the world the shop is in
# {NEAREST_WARP}        -> Warp nearest to shop
# -> Nearest warp only works with PlayerWarps v6.8.2 and above (https://www.spigotmc.org/resources/66692/)
#    If plugin is not installed/enabled, it ignores the line containing {NEAREST_WARP}
# -> Please don't put more than one placeholder in a single lore line
# -> If you don't want to show the below lore for any item,
#    set the below field as shop-gui-item-lore: []
shop-gui-item-lore:
  - ""
  - "&fPrice: &a${ITEM_PRICE}"
  - "&fStock: &7{SHOP_STOCK}"
  - "&fOwner: &7{SHOP_OWNER}"
  - "&fLocation: &7{SHOP_LOC}"
  - "&fWorld: &7{SHOP_WORLD}"
  - "&fWarp: &7{NEAREST_WARP}"
  - ""


# Set 'allow-direct-shop-tp' to true to allow players to teleport to the shop directly
# when they click on the shop result item in the GUI
# (Players require finditem.shoptp permission node)
# When set to false OR if players don't have permission,
# 'click-to-teleport-message' will not be shown in the lore
allow-direct-shop-tp: true
click-to-teleport-message: "&6&lClick to teleport to the shop!"
shop-tp-no-permission-message: "&cYou don't have permission to teleport to shop!"
unsafe-shop-area-message: "&cThe area around the shop is unsafe!"


shop-gui-back-button-material: "RED_CONCRETE"
shop-gui-back-button-text: "&7&l« &cBack"
shop-gui-next-button-material: "GREEN_CONCRETE"
shop-gui-next-button-text: "&aNext &7&l»"
shop-gui-filler-item: "GRAY_STAINED_GLASS_PANE"
shop-gui-close-button-material: "BARRIER"
shop-gui-close-button-text: "&fClose Search"
# Enter Item Custom Model Data below, if available, within quotes
# or leave as "" if not available
shop-gui-back-button-custom-model-data: ""
shop-gui-next-button-custom-model-data: ""
shop-gui-close-button-custom-model-data: ""


# Alert shown when player is already on first/last page and clicks back/next button
shop-navigation-first-page-alert-message: "&cYou are already on first page!"
shop-navigation-last-page-alert-message: "&cYou are already on last page!"


# Enabling this will spam your console with logs from the plugin
# Set this to true only for debugging purposes
# If set to false, some error messages can still get through if they require immediate attention
debug-mode: false