plugin-prefix: <#96eeff><b>Shop Search</b> <dark_gray>| <reset>
find-item-command:
  shop-search-loading-message: <white>Searching for shops...
  no-shop-found-message: <red>No shops found!
  invalid-shop-block-message: <red>Invalid shop block!
  shop-tp-banned-message: <red>You are banned from this shop!
shop-sorting-method: 2
search-loaded-shops-only: false
shop-search-gui-title: 'Shop Search: <matcher>'
shop-gui-item-lore:
  - ''
  - '<#96eeff>▎ <white>Price: <#fbf679>$<price>'
  - ''
  - '<#96eeff>▎ <white>Stock/Space: <gray><stock>'
  - '<#96eeff>▎ <white>Owner: <gray><owner>'
  - '<#96eeff>▎ <white>Location: <gray><location>'
  - '<#96eeff>▎ <white>World: <gray><world>'
  - '<#96eeff>▎ <white>Warp: <gray><warp>'
  - ''
  - '<white>⏩ <#96eeff>Left click<white> to teleport'
shop-gui:
  back-button-material: hdb-7827
  back-button-text: <#96eeff>Back
  next-button-material: hdb-7826
  next-button-text: <#96eeff>Next
  close-button-material: BARRIER
  close-button-text: <red>Close
ignore-empty-chests: true
blacklisted-worlds:
  - world_number_1
  - world_number_2