name: QSFindItemAddOn
version: ${project.version}
main: me.ronsane.finditemaddon.finditemaddon.FindItemAddOn
api-version: 1.13
authors: [ ronsane ]
depend:
  - QuickShop
softdepend:
  - PlayerWarps
  - PWarp
  - WorldGuard
  - Essentials

commands:
  finditem:
    description: Search for an item from shops
    aliases:
      - searchitem
      - shopsearch
      - searchshop

permissions:
  finditem.use:
    description: Enables players to use the /finditem command
    default: true
  finditem.hideshop:
    description: Enables players to use the /finditem hideshop & /finditem revealshop
    default: true
  finditem.reload:
    description: For OP. Enables use of '/finditem reload' to reload the config
    default: op
  finditem.restart:
    description: For OP. Enables use of '/finditem restart' to restart the plugin
    default: op
  finditem.updatelist:
    description: For OP. Enables use of '/finditem updatelist' to update warps list for essential warps
    default: op
  finditem.shoptp:
    description: If 'allow-direct-shop-tp' is enabled in config, players require this permission to be able to teleport
    default: op